-- Remove these modifications: Let the Community Patch do this fix

DELETE FROM "PolicyModifiers"
WHERE "ModifierId" IN ('STRATEGICAIRFORCE_MODERN_AIRFIGHTER_PRODUCTION', 'STRATEGICAIRFORCE_ATOMIC_AIRFIGHTER_PRODUCTION', 'STRATEGICAIRFORCE_ATOMIC_AIRBOMBER_PRODUCTION');

DELETE FROM "ModifierArguments"
WHERE "ModifierId" IN ('STRATEGICAIRFORCE_MODERN_AIRFIGHTER_PRODUCTION', 'STRATEGICAIRFORCE_ATOMIC_AIRFIGHTER_PRODUCTION', 'STRATEGICAIRFORCE_ATOMIC_AIRBOMBER_PRODUCTION');

DELETE FROM "Modifiers"
WHERE "ModifierId" IN ('STRATEGICAIRFORCE_MODERN_AIRFIGHTER_PRODUCTION', 'STRATEGICAIRFORCE_ATOMIC_AIRFIGHTER_PRODUCTION', 'STRATEGICAIRFORCE_ATOMIC_AIRBOMBER_PRODUCTION');
